import type { ProviderAdapter } from "../../types";

export const ERNIE_AI_STUDIO_BASE_URL = "https://aistudio.baidu.com/llm/lmapi/v3";
export const ERNIE_AI_STUDIO_API_KEY_ENV = "AI_STUDIO_API_KEY";
export const ERNIE_AI_STUDIO_DEFAULT_MODEL = "ernie-5.1";
export const ERNIE_AI_STUDIO_FALLBACK_MODELS = ["ernie-4.0-turbo-128k", "ernie-3.5-8k"];

export const PADDLEOCR_VL15_PROVIDER_ID = "paddleocr-vl15";
export const PADDLEOCR_VL15_DISPLAY_NAME = "PaddleOCR-VL Document Parsing Skill";
export const PADDLEOCR_VL15_API_KEY_ENV = "PADDLEOCR_API_KEY";
export const PADDLEOCR_VL15_DEFAULT_MODEL = "PaddleOCR-VL-1.6";
export const PADDLEOCR_VL15_DEFAULT_ENDPOINT = "";

export const paddleOcrVl15Provider = {
  id: PADDLEOCR_VL15_PROVIDER_ID,
  displayName: PADDLEOCR_VL15_DISPLAY_NAME,
  name: PADDLEOCR_VL15_DISPLAY_NAME,
  subtitle: "PaddleOCR-VL document parsing skill for PDF/image ingest, gated by endpoint and the configured API key env var.",
  subtitleZh: "PaddleOCR-VL 文档解析技能，用于 PDF / 图片 ingest，由 endpoint 和配置的 API key 环境变量门控。",
  providerType: "hosted",
  apiKeyEnv: PADDLEOCR_VL15_API_KEY_ENV,
  defaultModel: PADDLEOCR_VL15_DEFAULT_MODEL,
  defaultEndpoint: PADDLEOCR_VL15_DEFAULT_ENDPOINT,
  status: "missing_key",
} as const;

export const providerAdapters: ProviderAdapter[] = [
  {
    id: "ernie-ai-studio",
    displayName: "文心一言 / ERNIE",
    name: "文心一言 / ERNIE",
    subtitle: "Baidu AI Studio OpenAI-compatible ERNIE endpoint.",
    subtitleZh: "百度 AI Studio OpenAI 兼容文心一言端点。",
    kind: "api",
    providerType: "hosted",
    baseUrl: ERNIE_AI_STUDIO_BASE_URL,
    apiKeyEnv: ERNIE_AI_STUDIO_API_KEY_ENV,
    defaultModel: ERNIE_AI_STUDIO_DEFAULT_MODEL,
    fallbackModels: ERNIE_AI_STUDIO_FALLBACK_MODELS,
    models: [ERNIE_AI_STUDIO_DEFAULT_MODEL, ...ERNIE_AI_STUDIO_FALLBACK_MODELS],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    status: "missing_key",
    defaultApiBaseUrl: ERNIE_AI_STUDIO_BASE_URL,
    defaultApiKeyEnvVar: ERNIE_AI_STUDIO_API_KEY_ENV,
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 128000,
  },
  {
    id: "anthropic",
    displayName: "Anthropic (Claude)",
    name: "Anthropic (Claude)",
    subtitle: "Official Claude API using the Anthropic Messages wire.",
    subtitleZh: "官方 Claude API，使用 Anthropic Messages 协议。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "claude-sonnet-4-5-20250929",
    fallbackModels: [
      "claude-opus-4-7",
      "claude-opus-4-6",
      "claude-sonnet-4-6",
      "claude-haiku-4-5-20251001",
      "claude-3-5-sonnet-20241022",
    ],
    models: [
      "claude-sonnet-4-5-20250929",
      "claude-opus-4-7",
      "claude-opus-4-6",
      "claude-sonnet-4-6",
      "claude-haiku-4-5-20251001",
      "claude-3-5-sonnet-20241022",
    ],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.anthropic.com",
    defaultApiKeyEnvVar: "ANTHROPIC_API_KEY",
    defaultApiProtocol: "native",
    defaultContextWindow: 200000,
  },
  {
    id: "local-claude",
    displayName: "Local Claude",
    name: "Local Claude",
    subtitle: "Local Claude Code CLI handoff without storing API keys.",
    subtitleZh: "通过本地 Claude Code CLI 交接任务，不在桌面端保存 API key。",
    kind: "local",
    providerType: "local",
    command: "claude",
    defaultModel: "claude-sonnet-4-6",
    fallbackModels: ["claude-opus-4-7", "claude-opus-4-6", "claude-sonnet-4-5-20250929"],
    models: ["claude-sonnet-4-6", "claude-opus-4-7", "claude-opus-4-6", "claude-sonnet-4-5-20250929"],
    defaultContextWindow: 200000,
  },
  {
    id: "local-codex",
    displayName: "Local Codex",
    name: "Local Codex",
    subtitle: "Local Codex CLI handoff without storing API keys.",
    subtitleZh: "通过本地 Codex CLI 交接任务，不在桌面端保存 API key。",
    kind: "local",
    providerType: "local",
    command: "codex",
    defaultModel: "gpt-5.4-mini",
    fallbackModels: ["gpt-5.4", "gpt-5.3-codex", "gpt-5.3-codex-spark", "gpt-5.2"],
    models: ["gpt-5.4-mini", "gpt-5.4", "gpt-5.3-codex", "gpt-5.3-codex-spark", "gpt-5.2"],
    defaultContextWindow: 200000,
  },
  {
    id: "openai",
    displayName: "OpenAI (GPT)",
    name: "OpenAI (GPT)",
    subtitle: "Official OpenAI API using the OpenAI-compatible chat completions wire.",
    subtitleZh: "官方 OpenAI API，使用 OpenAI 兼容 chat completions 协议。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "gpt-4o",
    fallbackModels: ["gpt-4o-mini", "gpt-4.1", "gpt-4.1-mini", "o3", "o3-mini"],
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "o3", "o3-mini", "o1"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.openai.com/v1",
    defaultApiKeyEnvVar: "OPENAI_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 128000,
  },
  {
    id: "google",
    displayName: "Google (Gemini)",
    name: "Google (Gemini)",
    subtitle: "Google Generative Language API with native Gemini requests.",
    subtitleZh: "Google Generative Language API，使用 Gemini 原生请求。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "gemini-2.5-flash",
    fallbackModels: ["gemini-2.5-pro", "gemini-2.5-flash-lite", "gemini-2.0-flash", "gemini-1.5-flash"],
    models: ["gemini-2.5-flash", "gemini-2.5-pro", "gemini-2.5-flash-lite", "gemini-2.0-flash", "gemini-2.0-flash-lite", "gemini-1.5-pro", "gemini-1.5-flash"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultApiKeyEnvVar: "GOOGLE_API_KEY",
    defaultApiProtocol: "native",
    defaultContextWindow: 1000000,
  },
  {
    id: "deepseek",
    displayName: "DeepSeek",
    name: "DeepSeek",
    subtitle: "OpenAI-compatible DeepSeek endpoint.",
    subtitleZh: "DeepSeek OpenAI 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "deepseek-v4-flash",
    fallbackModels: ["deepseek-v4-pro", "deepseek-chat", "deepseek-reasoner"],
    models: ["deepseek-v4-flash", "deepseek-v4-pro", "deepseek-chat", "deepseek-reasoner"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.deepseek.com/v1",
    defaultApiKeyEnvVar: "DEEPSEEK_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 64000,
  },
  {
    id: "groq",
    displayName: "Groq",
    name: "Groq",
    subtitle: "Groq OpenAI-compatible endpoint for hosted open-weight models.",
    subtitleZh: "Groq OpenAI 兼容端点，面向托管开源权重模型。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "llama-3.3-70b-versatile",
    fallbackModels: ["llama-3.1-8b-instant", "llama-3.1-70b-versatile", "moonshotai/kimi-k2-instruct"],
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "llama-3.1-70b-versatile", "moonshotai/kimi-k2-instruct", "qwen/qwen3-32b"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.groq.com/openai/v1",
    defaultApiKeyEnvVar: "GROQ_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 128000,
  },
  {
    id: "xai",
    displayName: "xAI (Grok)",
    name: "xAI (Grok)",
    subtitle: "xAI OpenAI-compatible endpoint.",
    subtitleZh: "xAI OpenAI 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "grok-3",
    fallbackModels: ["grok-4-latest", "grok-4", "grok-3-mini", "grok-code-fast-1"],
    models: ["grok-4-latest", "grok-4", "grok-3", "grok-3-mini", "grok-code-fast-1", "grok-2-vision-1212"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.x.ai/v1",
    defaultApiKeyEnvVar: "XAI_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 131072,
  },
  {
    id: "nvidia-nim",
    displayName: "NVIDIA NIM",
    name: "NVIDIA NIM",
    subtitle: "NVIDIA hosted OpenAI-compatible model catalog.",
    subtitleZh: "NVIDIA 托管 OpenAI 兼容模型目录。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "meta/llama-3.3-70b-instruct",
    fallbackModels: ["nvidia/llama-3.3-nemotron-super-49b-v1.5", "deepseek-ai/deepseek-v3.2", "minimaxai/minimax-m2.7"],
    models: ["meta/llama-3.3-70b-instruct", "nvidia/llama-3.3-nemotron-super-49b-v1.5", "deepseek-ai/deepseek-v3.2", "moonshotai/kimi-k2.6", "minimaxai/minimax-m2.7"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://integrate.api.nvidia.com/v1",
    defaultApiKeyEnvVar: "NVIDIA_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 128000,
  },
  {
    id: "kimi",
    displayName: "Kimi (Moonshot)",
    name: "Kimi (Moonshot)",
    subtitle: "Moonshot global OpenAI-compatible endpoint.",
    subtitleZh: "Moonshot 国际版 OpenAI 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "kimi-k2.6",
    fallbackModels: ["kimi-k2.5", "kimi-k2-thinking", "kimi-for-coding"],
    models: ["kimi-k2.6", "kimi-k2.5", "kimi-k2-thinking", "kimi-for-coding"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.moonshot.ai/v1",
    defaultApiKeyEnvVar: "MOONSHOT_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 256000,
  },
  {
    id: "kimi-cn",
    displayName: "Kimi (Moonshot, 中国)",
    name: "Kimi (Moonshot, 中国)",
    subtitle: "Moonshot China OpenAI-compatible endpoint.",
    subtitleZh: "Moonshot 中国区 OpenAI 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "kimi-k2.6",
    fallbackModels: ["kimi-k2.5", "kimi-k2-thinking", "kimi-for-coding"],
    models: ["kimi-k2.6", "kimi-k2.5", "kimi-k2-thinking", "kimi-for-coding"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.moonshot.cn/v1",
    defaultApiKeyEnvVar: "MOONSHOT_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 256000,
  },
  {
    id: "zhipu",
    displayName: "智谱 GLM (Zhipu)",
    name: "智谱 GLM (Zhipu)",
    subtitle: "Zhipu BigModel OpenAI-compatible endpoint.",
    subtitleZh: "智谱 BigModel OpenAI 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "glm-4.6",
    fallbackModels: ["glm-4.5", "glm-4.5-air", "glm-4.5-flash", "glm-4-plus"],
    models: ["glm-4.6", "glm-4.5", "glm-4.5-air", "glm-4.5-flash", "glm-4-plus", "glm-4-air", "glm-4-flash"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultApiKeyEnvVar: "ZHIPU_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 128000,
  },
  {
    id: "minimax-global",
    displayName: "MiniMax (Global)",
    name: "MiniMax (Global)",
    subtitle: "MiniMax Anthropic-compatible endpoint.",
    subtitleZh: "MiniMax Anthropic 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "MiniMax-M2.7",
    fallbackModels: ["MiniMax-M2.5"],
    models: ["MiniMax-M2.7", "MiniMax-M2.5"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.minimax.io/anthropic",
    defaultApiKeyEnvVar: "MINIMAX_API_KEY",
    defaultApiProtocol: "anthropic-compatible",
    defaultContextWindow: 200000,
  },
  {
    id: "minimax-cn",
    displayName: "MiniMax (中国)",
    name: "MiniMax (中国)",
    subtitle: "MiniMax China Anthropic-compatible endpoint.",
    subtitleZh: "MiniMax 中国区 Anthropic 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "MiniMax-M2.7",
    fallbackModels: ["MiniMax-M2.5"],
    models: ["MiniMax-M2.7", "MiniMax-M2.5"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.minimaxi.com/anthropic",
    defaultApiKeyEnvVar: "MINIMAX_API_KEY",
    defaultApiProtocol: "anthropic-compatible",
    defaultContextWindow: 200000,
  },
  {
    id: "bailian-coding",
    displayName: "阿里百炼 Coding Plan",
    name: "阿里百炼 Coding Plan",
    subtitle: "DashScope Coding Plan OpenAI-compatible endpoint.",
    subtitleZh: "DashScope 百炼 Coding Plan OpenAI 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "qwen3.6-plus",
    fallbackModels: ["kimi-k2.5", "glm-5", "MiniMax-M2.5", "qwen3.5-plus"],
    models: ["qwen3.6-plus", "kimi-k2.5", "glm-5", "MiniMax-M2.5", "qwen3.5-plus", "qwen3-coder-plus"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://coding.dashscope.aliyuncs.com/v1",
    defaultApiKeyEnvVar: "DASHSCOPE_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 131072,
  },
  {
    id: "xiaomi-mimo",
    displayName: "小米 MiMo (Xiaomi)",
    name: "小米 MiMo (Xiaomi)",
    subtitle: "Xiaomi MiMo OpenAI-compatible endpoint.",
    subtitleZh: "小米 MiMo OpenAI 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "mimo-v2.5-pro",
    fallbackModels: ["mimo-v2.5", "mimo-v2-flash", "mimo-v2-pro", "mimo-v2-omni"],
    models: ["mimo-v2.5-pro", "mimo-v2.5", "mimo-v2-flash", "mimo-v2-pro", "mimo-v2-omni"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://api.xiaomimimo.com/v1",
    defaultApiKeyEnvVar: "XIAOMI_MIMO_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 1000000,
  },
  {
    id: "volcengine-ark",
    displayName: "火山引擎 Ark (Volcengine)",
    name: "火山引擎 Ark (Volcengine)",
    subtitle: "Volcengine Ark Coding OpenAI-compatible endpoint.",
    subtitleZh: "火山引擎 Ark Coding OpenAI 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "Doubao-Seed-2.0-Code",
    fallbackModels: ["Doubao-Seed-2.0-pro", "Doubao-Seed-2.0-lite", "DeepSeek-V3"],
    models: ["Doubao-Seed-2.0-Code", "Doubao-Seed-2.0-pro", "Doubao-Seed-2.0-lite", "Doubao-Seed-Code", "DeepSeek-V3"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",
    defaultApiKeyEnvVar: "VOLCENGINE_ARK_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 128000,
  },
  {
    id: "ollama-local",
    displayName: "Ollama (Local)",
    name: "Ollama (Local)",
    subtitle: "Local Ollama, LM Studio, llama.cpp, vLLM, or LocalAI endpoint.",
    subtitleZh: "本地 Ollama、LM Studio、llama.cpp、vLLM 或 LocalAI 端点。",
    kind: "api",
    providerType: "local",
    defaultModel: "llama3.1",
    fallbackModels: ["qwen3", "deepseek-r1", "mistral"],
    models: ["llama3.1", "qwen3", "deepseek-r1", "mistral"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "http://localhost:11434/v1",
    defaultApiKeyEnvVar: "",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 32768,
  },
  {
    id: "ollama-cloud",
    displayName: "Ollama Cloud",
    name: "Ollama Cloud",
    subtitle: "Ollama Cloud OpenAI-compatible endpoint.",
    subtitleZh: "Ollama Cloud OpenAI 兼容端点。",
    kind: "api",
    providerType: "hosted",
    defaultModel: "gpt-oss:120b",
    fallbackModels: ["gpt-oss:20b", "qwen3-coder:480b", "kimi-k2:1t", "deepseek-v3.1:671b"],
    models: ["gpt-oss:120b", "gpt-oss:20b", "qwen3-coder:480b", "kimi-k2:1t", "deepseek-v3.1:671b"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://ollama.com/v1",
    defaultApiKeyEnvVar: "OLLAMA_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 128000,
  },
  {
    id: "custom",
    displayName: "Custom",
    name: "Custom",
    subtitle: "Custom OpenAI- or Anthropic-compatible gateway; requires local setup.",
    subtitleZh: "自定义 OpenAI 或 Anthropic 兼容网关；需要本地配置。",
    kind: "api",
    providerType: "custom",
    defaultModel: "custom-model",
    fallbackModels: [],
    models: ["custom-model"],
    supportsStructuredOutput: "model-dependent",
    supportsStreaming: "optional",
    defaultApiBaseUrl: "https://your-gateway.example.com/v1",
    defaultApiKeyEnvVar: "CUSTOM_LLM_API_KEY",
    defaultApiProtocol: "openai-compatible",
    defaultContextWindow: 128000,
  },
];

export const providerIdAliases: Record<string, ProviderAdapter["id"]> = {
  openai: "openai",
  "openai-compatible": "openai",
  "custom-openai": "custom",
  "codex-cli": "local-codex",
  "claude-code-cli": "local-claude",
  "claude-code": "local-claude",
  "baidu-qianfan": "ernie-ai-studio",
  minimax: "minimax-global",
  ollama: "ollama-local",
};
